apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: codemasterapp
spec:
  selector:
    app: mysql
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306
    nodePort: 31004
  type: NodePort


