apiVersion: v1
kind: Service
metadata:
  name: php-service
  namespace: codemasterapp
spec:
  selector:
    app: php
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
  

