apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: codemasterapp
spec:
  selector:
    app: phpmyadmin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31003
  type: NodePort

